### ISSUE TITLE
Investigate use of secret syncing mode

### ISSUE THREAD

**Issue by timmydo** [microsoft/AutoCrane#17]
Investigate whether it makes sense to provide a secret provider sync mode where secrets can be written to `emptyDir` (medium: memory) for use in pods that need secrets on the file system.

**Comment by timmydo** [comment]
sample config running as an init container:
```
      initContainers:
      - name: initsecrets
        image: autocrane
        imagePullPolicy: Always
        env:
          - name: AUTOCRANE_ARGS
            value: secretwriter
          - name: SecretWriter__Sources
            value: /secret/azptoken:adocc:myadoinstance:client-id-guid:azkv:key-vault-name:key-vault-secret-key-name
        volumeMounts:
        - name: secretdir
          mountPath: /secret
      serviceAccountName: adoagent
      volumes:
      - name: secretdir
        emptyDir:
          medium: Memory
```
